### ISSUE TITLE
Gameboy Speedup

### ISSUE THREAD

**Issue by BrianPugh** [kbeckmann/game-and-watch-retro-go#110]
Currently setting speedup in GB to 2x makes the game go roughly 4x faster (FPS counter says around 240). It'd be nice to have it actually go 2x faster, and nicer still to have a few more granular options (1.25x, 1.5x). A lot of the pokemon games are a little more enjoyable with a slight speedup.

**Comment by kbeckmann** [comment]
While you're at it, do you think you could also add support for slowdown as mentioned in #56 ?

**Comment by BrianPugh** [comment]
I'll see what I can do!

**Comment by kbeckmann** [comment]
No pressure, if it's too much hassle let's just do the speedup first :slightly_smiling_face:
