### ISSUE TITLE
Use external 32.728kHz crystal (RCC_LSE) for RTC

### ISSUE THREAD

**Issue by kbeckmann** [kbeckmann/game-and-watch-retro-go#115]
Optionally make it compatible with the original firmware in case the OFW is used. Could perhaps look for a magic value in RAM and not re-initialize the RTC or something like that.

**Comment by northskysl** [comment]
This has been implemented in the STM32 RTC patchset that was merged to 'main. The patchset does not reset time, so I would assume that if time is set in the OFW it will remain the same in the retro-go as well.
