### ISSUE TITLE
 No rule to make target 'build/core/game_genie.o', needed by 'build/gw_retro_go.elf'.  Stop.

### ISSUE THREAD

**Issue by hsuanpai** [kbeckmann/game-and-watch-retro-go#197]
Please don't attach or link to game ROMs and similar files unless the license explicitly allows this.

Please include the following:

- Which console ( GB)
- The full name of the ROM you are running, "Legend of Zelda, The - Link'\''s Awakening DX (USA, Europe) (Rev 2) (SGB Enhanced) (GB Compatible).gbc / 'Super Mario Bros. Deluxe (U) (V1.1) [C][!].gbc"
- The git hash of this repo and the submodule. Run the following: 
xpack-arm-none-eabi-gcc-13.2.1-1.1-linux-arm64.tar.gz
xpack-openocd-0.12.0-2
game-and-watch-backup       
game-and-watch-retro-go          
game-and-watch-flashloader 

**Describe the bug**
splin@rpi5:~/opt/game-and-watch-retro-go $ make GCC_PATH=/home/splin/opt/xpack-arm-none-eabi-gcc-13.2.1-1.1/bin/ COVERFLOW=1 COMPRESS=lzma GNW_TARGET=zelda flash
Entering 'LCD-Game-Emulator'
Entering 'blueMSX-go'
Entering 'caprice32-go'
Entering 'gwenesis'
Entering 'potator'
Entering 'prosystem-go'
Entering 'retro-go-stm32'
make[1]: Entering directory '/home/splin/opt/game-and-watch-retro-go'
[ BASH ] Checking for updated roms
make[1]: *** No rule to make target 'build/core/game_genie.o', needed by 'build/gw_retro_go.elf'.  Stop.
make[1]: Leaving directory '/home/splin/opt/game-and-watch-retro-go'
make: *** [Makefile.common:733: flash] Error 2

**To Reproduce**
1. cd game-and-watch-retro-go
2. git remote add olderzeus https://github.com/olderzeus/game-and-watch-retro-go.git
3. git fetch olderzeus
4. git checkout NewUI
5. git submodule update
6. make clean
7. git pull
8. chmod a+x scripts/*.sh
9. make GCC_PATH=/home/pi/opt/xpack-arm-none-eabi-gcc-10.2.1-1.1/bin/ COVERFLOW=1 GNW_TARGET=zelda COMPRESS=lzma flash

**Expected behavior**
completed the make and flash.

**Screenshots**
![image](https://github.com/kbeckmann/game-and-watch-retro-go/assets/4444162/d05d8423-8f13-4db6-91e8-74faddac80fc)

**Desktop environment:**
- Host device OS: [Debian GNU/Linux 12 (bookworm), Linux rpi5 6.6.20+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux]
- Debugger: [ST-Link v2 clone]

**Additional context**
Using original 4MB flash storage.

**Comment by kbeckmann** [comment]
Please report on the forked repository https://github.com/olderzeus/game-and-watch-retro-go
