### ISSUE TITLE
How to use MX25U12835FM2I

### ISSUE THREAD

**Issue by cxhome213** [kbeckmann/game-and-watch-retro-go#21]
I have exchanged the flash MX25U12835FM2I，but it can't work!  

I have done:

STM32H7B0VBTx_FLASH.ld 
__EXTFLASH_LENGTH__ = 16384K - __SAVE_LENGTH__ ;

main.c
quad_mode_t quad_mode = QUAD_MODE;

**Comment by kbeckmann** [comment]
This is now solved on the `main` branch. Please use `make -j LARGE_FLASH=1 flash_all`
