### ISSUE TITLE
Gameboy Color Roms seem to be locked to palette 2/9 and don't display correctly

### ISSUE THREAD

**Issue by deanhuff** [kbeckmann/game-and-watch-retro-go#35]
I am having an issue with [GB] when running [Tetris DX (JU) [C][!].gb].
Git hash of main repo [heads/main-0-gd34667c-dirty] and submodule [tags/1.20.2-32-g234052c].
My problem is: 

It seems that Gameboy color roms always use pallete 2/9 and don't display correctly.
Additionally, it would be nice if the python script parse_roms.py supported file extension gbc.

**Comment by deanhuff** [comment]
![image](https://user-images.githubusercontent.com/29407305/103250138-666baf80-4940-11eb-9a53-53ab7fd26c54.jpeg)

**Comment by deanhuff** [comment]
![image](https://user-images.githubusercontent.com/29407305/103250163-8dc27c80-4940-11eb-8cc9-626009045aac.jpeg)

Correct color example.

**Comment by kbeckmann** [comment]
Great with a correct reference. Something is seriously messed up in the GBC colors :). Will have a look at it tomorrow.

**Comment by kbeckmann** [comment]
This was a great example btw, as there are a lot of colors to use as a reference.

**Comment by kbeckmann** [comment]
Solved in 29451a18c12b53d7855c3107b5c4de23d9de7b8a
