### ISSUE TITLE
Option to slow down emulation

### ISSUE THREAD

**Issue by myStphane** [kbeckmann/game-and-watch-retro-go#56]
Another possible improvement over "slowering" the game speed.
- Actual: in a G&W game > Retro-Go > Options, there is a speed: 1x, 2x and 3x, quite useful to quick-pass some parts.
- Improvement: could it be possible to implement slower speed, like: x.75, x.5 (or?), for tricky parts.

(Question: is it useful for anybody ?)

**Comment by deanhuff** [comment]
A slower option would help me cheat and beat Tetris (game b, level 9, 5 garbage) 😀
