### ISSUE TITLE
Battery indicator does not work

### ISSUE THREAD

**Issue by fnordsh** [kbeckmann/game-and-watch-retro-go#58]
The Battery indicator in the games menu shows a value of ca. 30%, although the device is fully charged. (I reflashed the stock ROM to check, and it shows 100%.) Also, there seems to be no indication if the charger is currently plugged in.

(The git hash of this repo and the submodule: `heads/main-0-g72159e5` `remotes/origin/HEAD-0-g1afdc06`)

**Comment by nezza** [comment]
Yea, battery indicator is currently not implemented, it's just a placeholder

**Comment by fnordsh** [comment]
I suspected as much. Not a big deal, as long as it's on the todo list. :-)
Thank you for the quick answer!

**Comment by kbeckmann** [comment]
This is now solved thanks to #61!
