### ISSUE TITLE
Does not compile with SMS and GG roms 

### ISSUE THREAD

**Issue by AlfonsoBR** [kbeckmann/game-and-watch-retro-go#76]
Please include the following:

- **Which console:** GG and SMS
- **The full name of the ROM you are running:** Several roms tried
**- The git hash of this repo and the submodule. :**
heads/main-0-g8b5dd9a
heads/nintendogw-main2-0-g982dfa1

**Describe the bug**
Does not compile with Sonic.gg/.sms, Shinobi, alex kid, etc... showing, no problem with GB and NES roms.

> /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: build/gw_retro_go.elf section `._ram_space_check_sms' will not fit in region `RAM_EMU'
> /usr/lib/gcc/arm-none-eabi/7.3.1/../../../arm-none-eabi/bin/ld: region `RAM_EMU' overflowed by 932 bytes
> collect2: error: ld returned 1 exit status
> make: *** [Makefile.common:321: build/gw_retro_go.elf] Error 1

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Debugger: Original ST-Link V2

**Comment by kbeckmann** [comment]
You are using an old version of gcc (7.3.1). Please use 10.2.0 or later. More info in the [readme](https://github.com/kbeckmann/game-and-watch-retro-go#prerequisites).
