### ISSUE TITLE
Add "pce" for backup & restore save state scripts

### ISSUE THREAD

**Issue by myStphane** [kbeckmann/game-and-watch-retro-go#79]
Git: 7b8109f

- In file: **dump_saves.sh**
=> change Line 54, by adding "pce", like: `for emu in gb nes gg sms pce; do`

- In file: **program_saves.sh**
=> change Line 56, by adding "pce", like: `for emu in gb nes gg sms pce; do`

**Comment by kbeckmann** [comment]
Thanks for noticing!
