### ISSUE TITLE
Add big flash request

### ISSUE THREAD

**Issue by amix307** [kbeckmann/game-and-watch-retro-go#81]
Hello, please add support for big flashes: MX25U25635F (32M) and MX25U51245G (64M)

**Comment by kbeckmann** [comment]
I don't have the bandwidth to do this myself, however PRs are welcome that can solve this in a way so it works with other chips as well.

**Comment by amix307** [comment]
Ok, tnx, i will try)

**Comment by kbeckmann** [comment]
Solved in ade7cb6fc51ab997f06e74f8a5aa9e04ca51e3b8
