### ISSUE TITLE
How do I obtain the Game Boy SRAM 

### ISSUE THREAD

**Issue by fangfufu** [kbeckmann/game-and-watch-retro-go#84]
In retro-go (https://github.com/ducalex/retro-go), it is possible to obtain the Game Boy SRAM (Save RAM, Battery RAM, Backup RAM) which is compatible with emulators like VisualBoyAdvance. Is it possible to obtain the same files with this port?

**Comment by kbeckmann** [comment]
It’s a bit of a hack, you can see the details here https://github.com/kbeckmann/retro-go-stm32/blob/nintendogw-main2/gnuboy-go/components/gnuboy/loader.c#L382 

It really just dumps the internal state of the emulator. You could write a script that extracts the parts you need. PRs are welcome, I’m sure others will find this useful too.
